### ISSUE TITLE
System agnostic approach possible?

### ISSUE THREAD

**Issue by SalieriC** [MKamysz/combat-effects-tracker#1]
I was requesting such a feature/module since 0.5.5! Absolutely needed imo. Just wish it were available as a system agnostic module. Do you think you could do that? Probably by having an option to manually set the used value.

**Comment by MKamysz** [comment]
Hey! Definitely! I'll work on something that allows choosing the value that is being used to count down the duration, but I can't promise anything regarding when it'll be available

**Comment by MKamysz** [comment]
Alrighty - I added some the functionality to choose which additional resource is tracked in the combat tracker, so that one is free to choose between AC, HP and whatever else exists 😄 

Hope this works for you!
