### ISSUE TITLE
AC and in person VTT

### ISSUE THREAD

**Issue by pixel7777** [MKamysz/combat-effects-tracker#2]
Sooo if you're running an in person game like me, opening the effect token to edit the AC is a non starter. It means the map moves all over the place. But if you used HP instead, other modules allow HP to be edited directly in the encounter tracker. Consider switching from AC to HP?

**Comment by MKamysz** [comment]
Uh, that's something I didn't consider at all, you're totally right! I'll work on a version that allows you to choose which attribute is used for the duration countdown, but I can't say anything about when it'll be available!

**Comment by MKamysz** [comment]
Hey Pixel!

I just pushed an update that allows you to choose which additional resource is tracked in your combat tracker under the module's settings - hope it works for you now 😀
