### ISSUE TITLE
Unable to access module settings

### ISSUE THREAD

**Issue by MNBlockhead** [MKamysz/combat-effects-tracker#3]
Instructions state: "Set the module settings to the correct resource that you use in your Combat Tracker"

In "configure settings" there is no section under the module settings for Combat Effects Tracker.  Any temporary combatants added with the [Effect] prefix do not have the values decrease.

**Comment by MKamysz** [comment]
Hey! 

I don't seem to able to reproduce your issue.

Did you make sure to activate the module for your current world first, under the **Manage Modules** section?

**Comment by MNBlockhead** [comment]
Yes, I have the module enabled.

[image: image.png]

But it doesn't appear in Settings/Module Settings:

[image: image.png]

Because of this, I can't set the tracked resource, so it just doesn't work.

Is there somewhere else to set the tracked resource other than Module
Settings?

Regards,

Paul

+1 651 373 2313

**Comment by MKamysz** [comment]
Hey Paul,

that's weird. Unfortunately, there is no other place to set the tracked resource (well, other than adjusting the code yourself of course).

Which game system are you using? Did you download the module via FoundryVTT, or did you paste the link to the JSON file yourself? If you did the latter, you may have accidentally used an old version of the module, which didn't yet include the option to track the resource. In this case, just delete the module and re-install it again from the **Add-On Modules** section in the configuration and setup of your FoundryVTT instance.

**Comment by MNBlockhead** [comment]
Okay, will do.  I'm hosting with The Forge, if that makes any difference.

Regards,

Paul

+1 651 373 2313

**Comment by MNBlockhead** [comment]
I tried uninstalling and reinstalling both by selecting it in the Ad-on
Modules dialog in Foundry and also by pasting in the URL to the json file.
Both given a warning that it may not work with Foundry version 0.6.5.

I wonder if it is conflicting with another module.

[image: image.png]
Regards,

Paul

+1 651 373 2313

**Comment by MKamysz** [comment]
Hey Paul,

sorry for the late reply. The warning is not related to your issue, it's a mess up in the configuration file on my part.

Not sure what's causing the issues, sorry that I can't be of more help!

**Comment by MNBlockhead** [comment]
No worries.  Thanks.

Regards,

Paul

+1 651 373 2313
